# Generated by Django 2.1.5 on 2019-02-13 05:02

from django.db import migrations, models
import djangohyper.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('content', djangohyper.fields.HyperField(blank=True, default='[]')),
            ],
        ),
    ]
