# Generated by Django 2.0.13 on 2019-12-05 04:19

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190305_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128),
        ),
    ]
