# Generated by Django 2.0.13 on 2019-12-05 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
