# Generated by Django 2.0.13 on 2020-02-04 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200202_0608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sts_password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sts_username',
        ),
    ]
