# Generated by Django 2.0.13 on 2020-02-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200204_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cert_client_code',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sts_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sts_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
