# Generated by Django 2.0.13 on 2020-02-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200204_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='max_free_trial_per_product',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='max_total_autodeploy',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
    ]
