# Generated by Django 2.0.13 on 2020-02-18 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0037_product_remote_menu_url'),
        ('core', '0012_auto_20200204_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('og_image', models.ImageField(upload_to='opengraph/')),
                ('og_title', models.CharField(blank=True, max_length=255, null=True)),
                ('og_description', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.Product')),
            ],
        ),
    ]
