# Generated by Django 2.0.13 on 2020-02-18 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_seoitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seoitem',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.Product'),
        ),
    ]
