# Django settings for website project.
#
# Generated by 'django-admin startproject' using Django 2.0.7.
#
# For more information on this file, see
# https://docs.djangoproject.com/en/2.0/topics/settings/
#
# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/2.0/ref/settings/
#

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))
BASE_DIR = os.path.dirname(PROJECT_DIR)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/


# Application definition

INSTALLED_APPS = [
    'base',
    'search',

    'wagtail.contrib.forms',
    'wagtail.contrib.redirects',
    'wagtail.embeds',
    'wagtail.sites',
    'wagtail.users',
    'wagtail.snippets',
    'wagtail.documents',
    'wagtail.images',
    'wagtail.search',
    'wagtail.admin',
    'wagtail.core',
    'wagtail.contrib.settings',
    'wagtail.contrib.modeladmin',
    "wagtail.contrib.routable_page",

    'wagtailmenus',

    'dit_common_core',
    'dit_email_addon',
    'wagtailhyper',
    'divineit',
    'treebeard',

    'modelcluster',
    'taggit',
    'compressor',
    'sekizai',
    'crispy_forms',
    'wagtailfontawesome',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',

    'captcha',
    'corsheaders'
]

MIDDLEWARE = [
    'django.middleware.gzip.GZipMiddleware',
    'base.middlewares.MinifyHTMLMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',

    'wagtail.core.middleware.SiteMiddleware',
    'wagtail.contrib.redirects.middleware.RedirectMiddleware',

    'base.middlewares.ThemeMiddleware',
]

ROOT_URLCONF = 'website.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(PROJECT_DIR, 'templates'),
        ],
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'base.context_processors.django_settings',
                'wagtail.contrib.settings.context_processors.settings',
                'sekizai.context_processors.sekizai',
                'wagtailmenus.context_processors.wagtailmenus',
            ],
            'loaders': (
                (
                    'base.loaders.ThemeLoader',
                    os.path.join(PROJECT_DIR, 'templates', 'themes')
                ),
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader',
            ),
        },
    },
]

WSGI_APPLICATION = 'website.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'compressor.finders.CompressorFinder'
]

STATICFILES_DIRS = [
    os.path.join(PROJECT_DIR, 'static'),
]

STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = '/static/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Wagtail settings

WAGTAIL_SITE_NAME = "divineit"

# Base URL to use when referring to full URLs within the Wagtail admin backend -
# e.g. in notification emails. Don't include '/admin' or a trailing slash
BASE_URL = 'http://example.com'

COMPRESS_CSS_FILTERS = ['compressor.filters.css_default.CssAbsoluteFilter', 'compressor.filters.cssmin.rCSSMinFilter']
COMPRESS_PRECOMPILERS = (
    ('text/scss', 'django_libsass.SassCompiler'),
)
COMPRESS_STORAGE = 'compressor.storage.GzipCompressorFileStorage'

COMPRESS_HTML = False

CRISPY_TEMPLATE_PACK = 'bootstrap4'

HYPER_EDITOR_BLOCK_CONFIG = {
    'slider': {
        'styles': [
            {'id': 'default', 'name': 'Default'},
            {'id': 'slider1', 'name': 'Testimonial slider'},
            {'id': 'slider2', 'name': 'Background image with text slider'},
            {'id': 'slider3', 'name': 'Success story slider'},
            {'id': 'slider4', 'name': 'Company history slider'},
            {'id': 'slider5', 'name': 'Background image slider with fixed height'},
            {'id': 'slider6', 'name': 'Slider blog style with link'},
            {'id': 'slider7', 'name': 'Slider image and content'},
            {'id': 'slider8', 'name': 'Background image with text slider center align'},
            {'id': 'slider9', 'name': 'Full screen slider'},
            {'id': 'slider11', 'name': 'revolution slider'},
            {'id': 'slider12', 'name': 'Testimonial-2 slider'},
            {'id': 'slider13', 'name': 'Client slider'},
            {'id': 'slider13.5', 'name': 'Client slider V2'},
            {'id': 'slider12.1', 'name': 'Homepage slider'},
            {'id': 'slider15', 'name': 'Service and product slider'},
            {'id': 'slider16', 'name': 'Partner slider'},
            {'id': 'slider17', 'name': 'Testimonial-3 slider'},
            {'id': 'slider17.1', 'name': 'Client testimonial-5 slider'},
            {'id': 'slider17.5', 'name': 'Product Slider'},
            {'id': 'slider25', 'name': 'revolution-2 slider'},
            {'id': 'slider25.5', 'name': 'Testimonial-5 slider'},
            {'id': 'slider26', 'name': 'Gallery slider'},
        ]
    },
    'layerslider': {
        'styles': [
            {'id': 'default', 'name': 'Default'},
            {'id': 'style1', 'name': 'Slider with image left and text right'},
            {'id': 'style2', 'name': 'Slider with image left'}
        ]
    },
    'contentbox': {
        'styles': [
            {'id': 'default', 'name': 'Default'},
            {'id': 'contentbox1', 'name': 'Counter box'},
            {'id': 'contentbox2', 'name': 'Content box without image'},
            {'id': 'contentbox3', 'name': 'Content box card with image'},
            {'id': 'contentbox4', 'name': 'Content box card without image'},
            {'id': 'contentbox5', 'name': 'Content box list type'},
            {'id': 'contentbox6', 'name': 'Content box type with link'},
            {'id': 'contentbox7', 'name': 'Content box type with link 2 img center top'},
            {'id': 'contentbox8', 'name': 'Content box call to action'},
            {'id': 'contentbox9', 'name': 'Counter box circle'},
            {'id': 'contentbox10', 'name': 'Border action button'},
            {'id': 'contentbox11', 'name': 'Solid action button'},
            {'id': 'contentbox14', 'name': 'Border action button white color'},
            {'id': 'contentbox12', 'name': 'Content box downloadable link'},
            {'id': 'contentbox13', 'name': 'Footer top call to action mobile'},
            {'id': 'contentbox13.1', 'name': 'Footer top call to action skype'},
            {'id': 'contentbox13.2', 'name': 'Footer top call to action email'},
            {'id': 'contentbox15', 'name': 'Counter box with link'},
            {'id': 'contentbox16', 'name': 'Content box card with image and link'},
            {'id': 'contentbox17', 'name': 'Content title and icon without link'},
            {'id': 'contentbox18', 'name': 'Title and icon fun-fact'},
            {'id': 'contentbox19', 'name': 'Content box blog'},
            {'id': 'contentbox20', 'name': 'Content overview title, thumbnail, short description and link'},
            {'id': 'contentbox21', 'name': 'Content product title, thumbnail, short description, link'},
        ]
    },
    'image': {
        'styles': [
            {'id': 'default', 'name': 'Default'},
            {'id': 'image1', 'name': 'Client image'}
        ]
    },
    'tab': {
        'styles': [
            {'id': 'default', 'name': 'Default'},
            {'id': 'tab1', 'name': 'Tab item center'},
            {'id': 'tab2', 'name': 'Tab item right'},
            {'id': 'tab3', 'name': 'Tab item left'}
        ]
    },
    'menu': {
        'styles': [
            {'id': 'default', 'name': 'Default'},
            {'id': 'menu1', 'name': 'Footer menu'},
            {'id': 'menu2', 'name': 'Menu with icon'},
            {'id': 'menu3', 'name': 'Menu second child'},
            {'id': 'menu4', 'name': 'Menu header top'},
            {'id': 'menu5', 'name': 'Menu with logo'},
            {'id': 'menu6', 'name': 'Menu with logo two'},
            {'id': 'menu7', 'name': 'Menu without logo'},
            {'id': 'menu8', 'name': 'Horizontal navbar'},
            {'id': 'menu9', 'name': 'Only footer menu'},
            {'id': 'menu11', 'name': 'Menu with submenu'},

        ]
    },
    'list': {
        'styles': [
            {'id': 'default', 'name': 'Default'},
            {'id': 'list1', 'name': 'list type tow column'},
            {'id': 'list2', 'name': 'image list for client'},
            {'id': 'list3', 'name': 'list with link & image'},
            {'id': 'list4', 'name': 'Contact call to action list'},
            {'id': 'list5', 'name': 'List with image, title and link'}
        ]
    },
    'customer': {
        'styles': [
            {'id': 'default', 'name': 'Default'},
            {'id': 'merquee', 'name': 'Merquee'}
        ]
    },
    'bullet_list': {
        'styles': [
            {'id': 'default', 'name': 'Default'},
            {'id': 'bullet1', 'name': 'Bullet without image'}
        ]
    },
    'news': {
        'styles': [
            {'id': 'default', 'name': 'Default'},
            {'id': 'timeline', 'name': 'Timeline News'},
            {'id': 'news-without-details', 'name': 'New Without Details'}
        ]
    },
    'news_paper': {
        'styles': [
            {'id': 'default', 'name': 'Default'},
            {'id': 'timeline', 'name': 'Timeline News'},
            {'id': 'news-without-details', 'name': 'New Without Details'}
        ]
    },
    'leadership': {
        'styles': [
            {'id': 'default', 'name': 'Default'},
            {'id': 'leadership', 'name': 'Leadership With Description'},
            {'id': 'leadership-1', 'name': 'Leadership four columns With Description'},
            {'id': 'leadership-2', 'name': 'Students with description'},
            {'id': 'leadership-3', 'name': 'Name designation social links'},
            {'id': 'leadership-4', 'name': 'leadership four columns'},
        ]
    },
    'imagegallery': {
        'styles': [
            {'id': 'default', 'name': 'Default'},
            {'id': 'imagegallery1', 'name': 'Single Image Zoom'},
            {'id': 'imagegallery2', 'name': 'Single Image Zoom V2'},
        ]
    },
    'videoslider': {
        'styles': [
            {'id': 'default', 'name': 'Default'},
            {'id': 'videoslider1', 'name': 'Video Slider V2'},
        ]
    },
    'socialBlock': {
        'styles': [
            {'id': 'default', 'name': 'Default'},
            {'id': 'socialStyle2', 'name': 'Social media style 2'},
            {'id': 'socialStyle3', 'name': 'Social media style 3'},
            {'id': 'socialStyle4', 'name': 'Social media style 4'},
            {'id': 'socialStyle5', 'name': 'Social media footer style 5'},
            {'id': 'socialStyle6', 'name': 'Social media footer style 6'},
        ]
    }
}

ENABLED_WAGTAIL_HYPER_MEGAMENU = True

HYPER_FORMS = [
    {'id': 'contact_form', 'title': 'Contact Form', 'class': 'base.forms.ContactForm'},
    {'id': 'contact_form_2', 'title': 'Contact Form Two', 'class': 'base.contact_form_2.NavanaContactForm'},
    {'id': 'contact_form_3', 'title': 'Contact Form Three', 'class': 'base.contact_form_3.ContactFormThree'},
    {'id': 'login_form', 'title': 'Login Form', 'class': 'divineit.forms.LoginForm'},
    {'id': 'ScheduleDemoForm', 'title': 'Schedule a Demo Form', 'class': 'divineit.forms.ScheduleDemoForm'},
    {'id': 'booking_form', 'title': 'Booking Form', 'class': 'base.booking_form.BookingFrom'},
    {'id': 'payment_verification', 'title': 'Verify payment form', 'class': 'base.payment_verification.VerifyPayment'},
    {'id': 'upcoming_event', 'title': 'Upcoming Event form', 'class': 'base.upcoming_event.UpcomingEventForm'},
    {'id': 'email_subscription', 'title': 'Email Subscription Form',
     'class': 'base.email_subscription.EmailSubscriptionFrom'},
    {'id': 'request_vapt', 'title': 'Custom Quote Form', 'class': 'base.request_vapt.VaptForm'},
    {'id': 'training_enroll', 'title': 'Course Enroll Form', 'class': 'base.training_enroll.TrainingForm'},
    {'id': 'download', 'title': 'Mail submit download Form', 'class': 'base.download.DownloadForm'},
    {'id': 'CustomQuoteForm', 'title': 'Schedule a Demo Form 2', 'class': 'base.request_vapt.CustomQuoteForm'},
    {'id': 'PartnerQuote', 'title': 'Partner Join Form', 'class': 'base.request_vapt.PartnerQuote'}
]

CONTACT_FORM_DEFAULT_PRODUCT = 'PrismERP'
CORS_ORIGIN_ALLOW_ALL = True

AVIABLE_THEMES = [
    'default',
    'theme-1',
    'theme-2',
    'theme-3',
    'theme-4',
    'theme-5',
    'theme-6',
    'theme-7',
    'theme-8',
    'theme-9',
    'theme-10',
    'theme-11',
    'theme-12',
    'theme-13',
    'theme-14'

]

KNOWLADGE_BASE_ENABLED = True

CONTACT_EMAIL = 'sales@divineit.net'
SILENCED_SYSTEM_CHECKS = ['captcha.recaptcha_test_key_error']

# Used for showing products from a remote oscar site that
# has oscar api. Some custom api might be required.
# Proper support only available for divine it website.
ENABLE_OSCAR_INTEGRATION = False
OSCAR_BASE_URL = 'http://pricingnew.divineit.net'
OSCAR_MENU_API = 'http://pricingnew.divineit.net/api/menu/'
