# Generated by Django 2.1.5 on 2019-02-06 11:19

from django.db import migrations
import djangohyper.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0002_auto_20190206_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatpage',
            name='content',
            field=djangohyper.fields.HyperField(blank=True, default='[]', verbose_name='Content'),
        ),
    ]
