# Generated by Django 2.0.8 on 2018-08-04 11:19

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('divineit', '0002_event_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatesSolutionToProduct',
            fields=[
                ('solution_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='divineit.Solution')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_solution_to_product', to='divineit.Product')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
            bases=('divineit.solution', models.Model),
        ),
    ]
