# Generated by Django 2.0.8 on 2018-08-04 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divineit', '0003_relatessolutiontoproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='product',
        ),
    ]
