# Generated by Django 2.0.8 on 2018-08-05 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20180804_0936'),
        ('divineit', '0004_remove_solution_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.StandardPage'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
