# Generated by Django 2.0.8 on 2018-08-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divineit', '0005_auto_20180805_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactperson',
            name='designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
