# Generated by Django 2.0.8 on 2018-08-05 11:49

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('divineit', '0006_contactperson_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='industries',
            field=modelcluster.fields.ParentalManyToManyField(to='divineit.Industry'),
        ),
        migrations.AddField(
            model_name='customer',
            name='products',
            field=modelcluster.fields.ParentalManyToManyField(to='divineit.Product'),
        ),
    ]
