# Generated by Django 2.0.8 on 2018-08-05 11:58

from django.db import migrations, models
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('divineit', '0008_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='services',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='divineit.Service'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='industries',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='divineit.Industry'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='products',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='divineit.Product'),
        ),
    ]
