# Generated by Django 2.0.8 on 2018-08-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divineit', '0009_auto_20180805_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactperson',
            name='contact_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
