# Generated by Django 2.0.8 on 2018-08-06 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divineit', '0011_auto_20180806_0647'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
