# Generated by Django 2.0.8 on 2018-08-07 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0020_add-verbose-name'),
        ('divineit', '0012_delete_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('expires', models.DateField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('job_type', models.TextField(blank=True, null=True)),
                ('experience', models.TextField(blank=True, null=True)),
                ('salary', models.TextField(blank=True, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='wagtailimages.Image')),
            ],
        ),
    ]
