# Generated by Django 2.0.8 on 2018-08-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divineit', '0013_career'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='title',
            field=models.CharField(max_length=155),
        ),
    ]
