# Generated by Django 2.0.8 on 2018-08-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divineit', '0015_customfield_relatescustomfieldtocarrer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='company_short_description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
