# Generated by Django 2.0.8 on 2018-08-13 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divineit', '0016_customer_company_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='company_short_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='expires',
            field=models.DateField(blank=True, null=True),
        ),
    ]
