# Generated by Django 2.0.8 on 2018-08-13 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0020_add-verbose-name'),
        ('divineit', '0017_auto_20180813_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='background_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_bg_image', to='wagtailimages.Image'),
        ),
    ]
