# Generated by Django 2.0.8 on 2018-08-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divineit', '0018_customer_background_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='company_short_description',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
