# Generated by Django 2.0.8 on 2018-08-16 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divineit', '0020_create_qoute_template'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relatescustomfieldtocarrer',
            old_name='page',
            new_name='career',
        ),
        migrations.RenameField(
            model_name='relatessolutiontoproduct',
            old_name='page',
            new_name='product',
        ),
    ]
