# Generated by Django 2.0.8 on 2018-08-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divineit', '0021_auto_20180816_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='rating',
            field=models.PositiveIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='show_in_site',
            field=models.BooleanField(default=True),
        ),
    ]
