# Generated by Django 2.0.8 on 2018-08-19 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divineit', '0024_auto_20180819_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kbcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='kbsubcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
