# Generated by Django 2.0.8 on 2018-08-19 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divineit', '0025_auto_20180819_0544'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Knowladge',
            new_name='Knowledge',
        ),
    ]
