# Generated by Django 2.0 on 2018-08-29 12:09

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('divineit', '0026_auto_20180819_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='solutions',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='divineit.Solution'),
        ),
    ]
