# Generated by Django 2.0 on 2018-08-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divineit', '0027_customer_solutions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='rating',
            field=models.PositiveIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29)], default=0, help_text='10 = View First, 0 = View Last'),
        ),
    ]
