# Generated by Django 2.0 on 2018-08-30 11:17

from django.db import migrations
import wagtailhyper.fields


class Migration(migrations.Migration):

    dependencies = [
        ('divineit', '0030_auto_20180830_0613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.RemoveField(
            model_name='news',
            name='description',
        ),
        migrations.AddField(
            model_name='event',
            name='content',
            field=wagtailhyper.fields.HyperField(default='[]'),
        ),
        migrations.AddField(
            model_name='news',
            name='content',
            field=wagtailhyper.fields.HyperField(default='[]'),
        ),
    ]
