# Generated by Django 2.0.8 on 2018-10-04 07:15

from django.db import migrations
import wagtailhyper.fields


class Migration(migrations.Migration):

    dependencies = [
        ('divineit', '0031_auto_20180830_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='description',
            field=wagtailhyper.fields.HyperField(default='[]'),
        ),
    ]
