# Generated by Django 2.0.8 on 2018-10-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divineit', '0032_auto_20181004_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='apply_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
