# Generated by Django 2.0.9 on 2018-12-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divineit', '0033_career_apply_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='detailsUrl',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
