# Generated by Django 2.0.13 on 2020-02-04 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0022_product_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0005_update_email_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('licence_type', models.CharField(choices=[('free-trial', 'Free Trial'), ('buy-now', 'Paid')], max_length=100)),
                ('status', models.IntegerField(blank=True, choices=[(0, 'Pending'), (1, 'Payment Complete'), (2, 'Updated to Licence Server')], default=0, null=True)),
                ('inactive', models.BooleanField(choices=[(0, 'NO'), (1, 'YES')], default=True)),
                ('deployment_status', models.IntegerField(blank=True, choices=[(0, 'Pending'), (1, 'In Progress'), (2, 'Error Occurred'), (3, 'Deployed[host unresolved]'), (4, 'Active'), (5, 'Inactive'), (6, 'Cancelled')], default=0, null=True)),
                ('app_user', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('app_pass', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('error', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('error_details', models.TextField(blank=True, default=None, null=True)),
                ('cert_subscription_code', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('sub_domain', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('domain', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField()),
                ('notification_flag', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='order.Line')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalogue.Product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
