# Generated by Django 2.0.13 on 2020-02-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodeploy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerecord',
            name='deployment_config',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='deployment_period',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
