# Generated by Django 2.0.13 on 2020-02-05 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autodeploy', '0002_auto_20200204_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deployment_status', models.IntegerField(blank=True, choices=[(0, 'Pending'), (1, 'In Progress'), (2, 'Error Occurred'), (3, 'Deployed[host unresolved]'), (4, 'Active'), (5, 'Inactive'), (6, 'Cancelled')], default=0, null=True)),
                ('app_user', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('app_pass', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('error', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('error_details', models.TextField(blank=True, default=None, null=True)),
                ('cert_subscription_code', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('sub_domain', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('domain', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('deployment_config', models.TextField(blank=True, default='{}', null=True)),
                ('deployment_period', models.IntegerField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='servicerecord',
            name='app_pass',
        ),
        migrations.RemoveField(
            model_name='servicerecord',
            name='app_user',
        ),
        migrations.RemoveField(
            model_name='servicerecord',
            name='cert_subscription_code',
        ),
        migrations.RemoveField(
            model_name='servicerecord',
            name='deployment_status',
        ),
        migrations.RemoveField(
            model_name='servicerecord',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='servicerecord',
            name='error',
        ),
        migrations.RemoveField(
            model_name='servicerecord',
            name='error_details',
        ),
        migrations.RemoveField(
            model_name='servicerecord',
            name='sub_domain',
        ),
        migrations.AddField(
            model_name='deployment',
            name='service_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autodeploy.ServiceRecord'),
        ),
    ]
