# Generated by Django 2.0.13 on 2020-02-05 04:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('autodeploy', '0003_auto_20200205_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerecord',
            name='cert_subscription_code',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='domain',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='sub_domain',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
