# Generated by Django 2.0.13 on 2020-02-05 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodeploy', '0004_auto_20200205_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='product_code',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='product_code',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
