# Generated by Django 2.0.13 on 2020-02-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodeploy', '0005_auto_20200205_0453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deployment',
            old_name='domain',
            new_name='domain_code',
        ),
        migrations.RenameField(
            model_name='servicerecord',
            old_name='domain',
            new_name='domain_code',
        ),
        migrations.AddField(
            model_name='deployment',
            name='domain_ext',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='domain_ext',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
    ]
