# Generated by Django 2.0.13 on 2020-02-20 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodeploy', '0006_auto_20200209_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerecord',
            name='approved_for_deploy',
            field=models.BooleanField(default=False),
        ),
    ]
