# Generated by Django 2.1.5 on 2019-02-10 14:00

from django.db import migrations
import djangohyper.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0013_auto_20170821_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=djangohyper.fields.HyperField(blank=True, default='[]'),
        ),
    ]
