# Generated by Django 2.0.13 on 2019-08-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0016_auto_20190304_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_icon',
            field=models.ImageField(blank=True, default=None, max_length=255, null=True, upload_to='categories', verbose_name='Image'),
        ),
    ]
