# Generated by Django 2.0.13 on 2019-08-21 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0017_category_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_icon',
            field=models.ImageField(blank=True, default=None, max_length=255, null=True, upload_to='categories', verbose_name='Icon'),
        ),
    ]
