# Generated by Django 2.0.13 on 2019-08-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0018_auto_20190821_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='banner_image',
            field=models.ImageField(blank=True, default=None, max_length=255, null=True, upload_to='images', verbose_name='Banner Image'),
        ),
    ]
