# Generated by Django 2.0.13 on 2019-11-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0019_product_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productclass',
            name='can_be_customized',
            field=models.BooleanField(default=False),
        ),
    ]
