# Generated by Django 2.0.13 on 2019-12-19 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0021_product_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='logo',
            field=models.ImageField(blank=True, default=None, max_length=255, null=True, upload_to='logos', verbose_name='Logo'),
        ),
    ]
