# Generated by Django 2.0.13 on 2020-02-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0022_product_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='auto_deploy_enable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='auto_deploy_metrics',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='auto_deploy_period',
            field=models.IntegerField(blank=True, default=30, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='free_trial_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='free_trial_period',
            field=models.IntegerField(blank=True, default=30, null=True),
        ),
    ]
