# Generated by Django 2.0.13 on 2020-02-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0023_auto_20200204_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='free_trial_metrics',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
    ]
