# Generated by Django 2.0.13 on 2020-02-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0024_product_free_trial_metrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='auto_deploy_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
