# Generated by Django 2.0.13 on 2020-02-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0025_product_auto_deploy_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='auto_deploy_domain_code',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='auto_deploy_domain_ext',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
    ]
