# Generated by Django 2.0.13 on 2020-02-11 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0026_auto_20200209_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ordering',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
