# Generated by Django 2.0.13 on 2020-02-13 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0027_product_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dummy',
            field=models.BooleanField(default=False),
        ),
    ]
