# Generated by Django 2.0.13 on 2020-02-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0029_product_pricing_detail_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ask_for_quote_form_link',
            field=models.CharField(blank=True, default=False, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='only_ask_for_quote',
            field=models.BooleanField(default=False),
        ),
    ]
