# Generated by Django 2.0.13 on 2020-02-13 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0031_auto_20200213_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ask_for_quote_form_link',
            field=models.URLField(blank=True, default=None, max_length=255),
        ),
    ]
