# Generated by Django 2.0.13 on 2020-02-13 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0032_auto_20200213_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ask_for_quote_form_link',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='pricing_detail_link',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
    ]
