# Generated by Django 2.0.13 on 2020-02-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0036_auto_20200217_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='remote_menu_url',
            field=models.URLField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
