# Generated by Django 2.0.13 on 2020-02-20 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0037_product_remote_menu_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='auto_deploy_approval_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='inactive',
            field=models.BooleanField(default=False),
        ),
    ]
