# Generated by Django 2.0.7 on 2018-07-29 04:53

from django.db import migrations, models
import django.db.models.deletion
import wagtailhyper.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20180717_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationsettings',
            name='header_top',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.BasicSnippet'),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='content',
            field=wagtailhyper.fields.HyperField(blank=True, default='[]', null=True),
        ),
    ]
