# Generated by Django 2.0.7 on 2018-07-23 19:50

from django.db import migrations
import wagtailhyper.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20180717_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardpage',
            name='content',
            field=wagtailhyper.fields.HyperField(blank=True, default='[]', null=True),
        ),
    ]
