# Generated by Django 2.0.7 on 2018-07-29 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20180723_1950'),
        ('base', '0004_auto_20180729_0453'),
    ]

    operations = [
    ]
