# Generated by Django 2.0.8 on 2018-08-04 06:06

from django.db import migrations

def create_email_tempates(apps, schema_editor):
    EmailTemplate = apps.get_model('dit_email_addon', 'EmailTemplate')
    EmailTemplate.objects.get_or_create(
        code="contact",
        defaults={
            'title': 'Contact Email to Admin',
            'subject': 'New Contact form submitted',
            'body': ''' <html><body>
                    Name: {{ name }}<br>
                    Company Name: {{ company_name }}<br>
                    Phone: {{ phone }}<br>
                    Email: {{ email }}<br>
                    Country: {{ country }}<br>
                    Message: {{ message }}<br>

                    </body></html>'''
        }
    )

    EmailTemplate.objects.get_or_create(
        code="contact_reply",
        defaults={
            'title': 'Contact Email Reply to User',
            'subject': 'Thank You for Contacting Us',
            'body': ''' <html><body>
                    <h2>Thank You for contacting Us</h2>
                    <p>We will get back to you soon!</p>
                    </body></html>'''
        }
    )

class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_merge_20180729_1231'),
        ('dit_email_addon', '0004_auto_20180728_0552'),
    ]

    operations = [
        migrations.RunPython(create_email_tempates),
    ]
