# Generated by Django 2.0.8 on 2018-08-04 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_contact_form_email_templates_20180804_0606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standardpage',
            name='repeat_in_subnav',
        ),
        migrations.RemoveField(
            model_name='standardpage',
            name='repeated_item_text',
        ),
    ]
