# Generated by Django 2.0.8 on 2018-08-04 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmenus', '0022_auto_20170913_2125'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailhyper', '0011_delete_form'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0040_page_draft_title'),
        ('base', '0007_auto_20180804_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkpage',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='linkpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='LinkPage',
        ),
    ]
