# Generated by Django 2.0.8 on 2018-08-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20180804_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationsettings',
            name='product_toolbar_base_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
