# Generated by Django 2.0.8 on 2018-08-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_applicationsettings_product_toolbar_base_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationsettings',
            name='theme',
            field=models.CharField(choices=[('default', 'default'), ('theme-1', 'theme-1')], default='default', help_text='Select which theme to use', max_length=255),
        ),
    ]
