# Generated by Django 2.0 on 2018-08-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20180829_0947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='standardpage',
            old_name='site_map_priority',
            new_name='priority',
        ),
        migrations.AddField(
            model_name='standardpage',
            name='changefreq',
            field=models.CharField(choices=[('always', 'always'), ('hourly', 'hourly'), ('daily', 'daily'), ('weekly', 'weekly'), ('monthly', 'monthly'), ('yearly', 'yearly'), ('never', 'never')], default='daily', max_length=15),
        ),
    ]
