# Generated by Django 2.0.8 on 2018-10-01 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20180829_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationsettings',
            name='theme',
            field=models.CharField(choices=[('default', 'default'), ('theme-1', 'theme-1'), ('theme-2', 'theme-2')], default='default', help_text='Select which theme to use', max_length=255),
        ),
    ]
