# Generated by Django 2.0.8 on 2018-10-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20181001_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationsettings',
            name='gtags_container_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
