# Generated by Django 2.0.9 on 2018-10-16 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_applicationsettings_gtags_container_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardpage',
            name='seo',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
