# Generated by Django 2.0.9 on 2018-12-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20181016_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationsettings',
            name='theme',
            field=models.CharField(choices=[('default', 'default'), ('theme-1', 'theme-1'), ('theme-2', 'theme-2'), ('theme-3', 'theme-3'), ('theme-4', 'theme-4'), ('theme-5', 'theme-5')], default='default', help_text='Select which theme to use', max_length=255),
        ),
    ]
