# Generated by Django 2.0.13 on 2019-05-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20181224_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationsettings',
            name='theme',
            field=models.CharField(choices=[('default', 'default'), ('theme-1', 'theme-1'), ('theme-2', 'theme-2'), ('theme-3', 'theme-3'), ('theme-4', 'theme-4'), ('theme-5', 'theme-5'), ('theme-6', 'theme-6'), ('theme-7', 'theme-7'), ('theme-8', 'theme-8'), ('theme-9', 'theme-9')], default='default', help_text='Select which theme to use', max_length=255),
        ),
    ]
