# Generated by Django 2.0.13 on 2020-01-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_auto_20190905_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationsettings',
            name='theme',
            field=models.CharField(choices=[('default', 'default'), ('theme-1', 'theme-1'), ('theme-2', 'theme-2'), ('theme-3', 'theme-3'), ('theme-4', 'theme-4'), ('theme-5', 'theme-5'), ('theme-6', 'theme-6'), ('theme-7', 'theme-7'), ('theme-8', 'theme-8'), ('theme-9', 'theme-9'), ('theme-10', 'theme-10'), ('theme-11', 'theme-11'), ('theme-12', 'theme-12'), ('theme-13', 'theme-13')], default='default', help_text='Select which theme to use', max_length=255),
        ),
    ]
