# Generated by Django 2.0.13 on 2020-01-29 06:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_auto_20200105_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentVerify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=25, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+880121234543'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.CharField(max_length=25)),
                ('txn_id', models.CharField(max_length=25)),
                ('payment_method', models.CharField(max_length=25)),
                ('team_name', models.CharField(max_length=50)),
                ('leader_name', models.CharField(max_length=50)),
                ('member_one_name', models.CharField(max_length=50)),
                ('member_two_name', models.CharField(max_length=50)),
                ('member_three_name', models.CharField(max_length=50)),
                ('leader_email', models.EmailField(max_length=254, unique=True)),
                ('university_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('session', models.CharField(max_length=100)),
                ('leader_phone', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+880121234543'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
            ],
        ),
        migrations.AlterField(
            model_name='applicationsettings',
            name='theme',
            field=models.CharField(choices=[('default', 'default'), ('theme-1', 'theme-1'), ('theme-2', 'theme-2'), ('theme-3', 'theme-3'), ('theme-4', 'theme-4'), ('theme-5', 'theme-5'), ('theme-6', 'theme-6'), ('theme-7', 'theme-7'), ('theme-8', 'theme-8'), ('theme-9', 'theme-9'), ('theme-10', 'theme-10'), ('theme-11', 'theme-11'), ('theme-12', 'theme-12'), ('theme-13', 'theme-13'), ('theme-14', 'theme-14')], default='default', help_text='Select which theme to use', max_length=255),
        ),
    ]
