# Generated by Django 2.0.13 on 2020-04-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_auto_20200105_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationsettings',
            name='extra_header_context',
            field=models.TextField(blank=True, default=None, max_length=2000, null=True),
        ),
    ]
