# Generated by Django 2.0.13 on 2020-01-29 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_auto_20200129_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentverify',
            name='leader_email',
            field=models.EmailField(max_length=254),
        ),
    ]
