# Generated by Django 2.0.13 on 2020-04-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_applicationsettings_extra_header_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardpage',
            name='head_context',
            field=models.TextField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
