# Generated by Django 2.0.13 on 2020-02-10 08:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_auto_20200129_0733'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('department_name', models.CharField(max_length=30)),
                ('session', models.CharField(max_length=25)),
                ('contact_number', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+880121234543'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('emergency_number', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+880121234543'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('linkedIn_profile', models.URLField()),
                ('drop_resume', models.FileField(upload_to='UpcomingEvent')),
                ('profile_photo', models.ImageField(upload_to='UpcomingEvent')),
                ('about_youself', models.TextField(max_length=200)),
                ('three_best_skill', models.TextField()),
                ('experience', models.CharField(max_length=50)),
                ('public_speaking', models.CharField(max_length=100)),
                ('technical_skills', models.TextField()),
                ('why_join_us', models.TextField()),
                ('SDC_future_goal', models.TextField(max_length=150)),
                ('involved_any_other_club', models.CharField(max_length=100)),
                ('do_you_for_SDC', models.CharField(max_length=70)),
            ],
        ),
    ]
