# Generated by Django 2.0.13 on 2020-02-10 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_upcomingevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upcomingevent',
            old_name='emergency_number',
            new_name='emergency_contact_number',
        ),
    ]
