# Generated by Django 2.0.13 on 2020-02-10 08:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_auto_20200210_0803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upcomingevent',
            old_name='about_youself',
            new_name='about_yourself',
        ),
        migrations.AlterField(
            model_name='upcomingevent',
            name='contact_number',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+880121234543'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,14}$')]),
        ),
        migrations.AlterField(
            model_name='upcomingevent',
            name='emergency_contact_number',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+880121234543'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,14}$')]),
        ),
        migrations.AlterField(
            model_name='upcomingevent',
            name='session',
            field=models.CharField(max_length=14),
        ),
    ]
