# Generated by Django 2.0.13 on 2020-02-10 11:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_auto_20200210_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcomingevent',
            name='SDC_future_goal',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='upcomingevent',
            name='contact_number',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+880121234543'. Up to 14 digits allowed.", regex='^\\+?1?\\d{9,14}$')]),
        ),
        migrations.AlterField(
            model_name='upcomingevent',
            name='drop_resume',
            field=models.FileField(blank=True, null=True, upload_to='UpcomingEvent'),
        ),
        migrations.AlterField(
            model_name='upcomingevent',
            name='emergency_contact_number',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+880121234543'. Up to 14 digits allowed.", regex='^\\+?1?\\d{9,14}$')]),
        ),
        migrations.AlterField(
            model_name='upcomingevent',
            name='experience',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='upcomingevent',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='UpcomingEvent'),
        ),
    ]
