# Generated by Django 2.0.13 on 2020-02-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_auto_20200210_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcomingevent',
            name='about_yourself',
            field=models.TextField(),
        ),
    ]
