# Generated by Django 2.0.13 on 2020-02-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_auto_20200210_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcomingevent',
            name='involved_any_other_club',
            field=models.CharField(max_length=500),
        ),
    ]
