# Generated by Django 2.0.13 on 2020-02-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_auto_20200210_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingevent',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='upcomingevent',
            name='id_no',
            field=models.CharField(blank=True, default=None, max_length=25, null=True),
        ),
    ]
