# Generated by Django 2.0 on 2020-04-09 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_emailsubscription'),
        ('base', '0022_standardpage_head_context'),
    ]

    operations = [
    ]
