# Generated by Django 2.0 on 2020-05-08 10:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_merge_20200409_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentForm3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('phone', models.CharField(max_length=25, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+880121234543'. Up to 14 digits allowed.", regex='^\\+?1?\\d{9,14}$')])),
                ('email_address', models.EmailField(max_length=25)),
                ('company_name', models.CharField(blank=True, max_length=90, null=True)),
                ('message', models.TextField()),
            ],
        ),
    ]
