# Generated by Django 2.0.13 on 2019-11-30 06:53

from django.db import migrations, models
import pricing.pyapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=40, unique=True)),
                ('configuration', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PricingVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_sheet_id', models.CharField(blank=True, max_length=255, null=True)),
                ('parsed_json', models.TextField(blank=True, null=True)),
                ('downloaded_file', models.FileField(blank=True, max_length=255, null=True, upload_to=pricing.pyapp.models.get_file_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
