# Generated by Django 2.0.13 on 2019-12-10 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0020_productclass_can_be_customized'),
        ('pyapp', '0002_auto_20191208_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.Product'),
        ),
    ]
