# Generated by Django 2.0.13 on 2019-12-15 06:25

from django.db import migrations, models
import django.db.models.deletion
import ecommerce.quotation.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0005_update_email_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_docx', models.FileField(max_length=255, upload_to=ecommerce.quotation.models.get_file_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
            ],
        ),
    ]
