# Generated by Django 2.0.13 on 2019-12-15 09:21

from django.db import migrations, models
import ecommerce.quotation.models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='generated_docx',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=ecommerce.quotation.models.get_file_path),
        ),
    ]
