# Generated by Django 2.0.13 on 2020-01-09 10:02

from django.db import migrations, models
import ecommerce.quotation.models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0002_auto_20191215_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='generated_pdf',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=ecommerce.quotation.models.get_file_path),
        ),
    ]
